#Una escuela aplica dos exámenes a sus aspirantes, por lo que cada uno de ellos 
# obtiene dos calificaciones denotadas como C1 y C2. El aspirante que obtenga
# calificaciones mayores que 80 en ambos exámenes es aceptado; en caso contrario
# es rechazado.

class Tarea ():
    def __init__():
        pass
    def cond_and(self):
     c1= int(input("Esciba la nota de su primer examen: "))
     c2= int(input("Esciba la nota de su segundo examen: "))
     if c1 >= 80 and c2 >= 80:
      print("Felicidades usted ha sido  aceptado!")
    
     else: print("Lo sentimos usted ha sido rechazado")
     
eje= Tarea()
eje.cond_and()
    